apiVersion: apps/v1 # Stateful set for mongo
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: karsajobs
spec: # Stateful set specifications
  selector:
    matchLabels:
      app: karsajobs
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: karsajobs
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
            - name: mongodb-config
              mountPath: /config
            - name: mongodb-secret
              mountPath: /etc/mongo-credentials
          ports:
            - name: mongodb
              containerPort: 27017
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: mongodb-config
          configMap:
            name: mongodb-config
            items:
              - key: mongo.conf
                path: mongo.conf
        - name: mongodb-secret
          secret:
            secretName: mongodb-secret
